### ISSUE TITLE
Finnish User Instruction

### ISSUE THREAD

**Issue by HannuHyttinen** [Sensotrend/sensotrend-uploader#30]
When creating a request, please fill in parts 1 and 2 with as much information as possible. A good description is most important for us. Fields in the part 2 can also be filled when analyzing the issue.

### 1. Description
Suomenkieliset käyttöohjeet Uploaderille. Tre kaupungin diabetesvastaanoton toiveena on, että käyttöohjeet olisivat laitekohtaiset. Sekä sähköiset että pdf-muotoiset ohjeet tarvitaan.

### 2. Requirements and dependencies
Known requirements for
- functional: Tarvitaan kysymyksiä/vastauksia osio.
- performance: -
- usability: Pitää toimia yleisimmillä selaimilla, myös IE.
- safety: -

Identified potential risks to the patient: Jos käyttöohje on huono, ei palvelu välttämättä ole kaikkien käyttäjien käytettävissä heidän IT-osaamisellaan.
Dependencies on other issues: -
Target schedule: Tarvitaan Tre kaupungin diabetesvastaanotot beta-vaiheeseen.

### 3. Implementation details
Implementation plan: Hannu tekee sisältöä ja Timo react-toteutusta.

### 3.1 OWASP top 10
N/A

### 4. Verification

Verifivation plan: Testataan Uploadaus mahdollisimman monilla eri laitteilla. Varmistetaan samalla, että toimii kuten käyttöohjeissa sanotaan.

Verification results:
(Ennen marraskuuta tehdyissä testeissä ei ole ollut käyttöohjetta käytettävissä.)

- [x] Abbott FreeStyle Libre: Date: 30.9.2020, Uploader rel: 2.33.0-alpha, Result: PASS
- [ ] Abbott FreeStyle Lite: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Abbott Freedom Lite: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [x] Abbott FreeStyle Precision Neo: Date: 3.11.2020, Uploader rel: 2.33.0-alpha, Result: PASS,  Sensotrend/sensotrend-uploader#31  
- [ ] Abbott FreeStyle Optium Neo: Date: dd.mm.yyyy, Uploader rel: release number. Result: 
- [ ] Abbott Precision Xtra: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Animas: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [x] Ascensia (Bayer) Contour Next: Date: 19.8.2020, Uploader rel: ?, Result: PASS
- [ ] Ascensia (Bayer) Contour Next EZ: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Ascensia (Bayer) Contour: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Ascensia (Bayer) Contour Link: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [x] CareSens N Premier: Date: 3.11.2020, Uploader rel: 2.33.0-alpha, Result: FAIL,  Sensotrend/sensotrend-uploader#32  
- [x] CareSens Dual: Date: 3.11.2020, Uploader rel: 2.33.0-alpha, Result: FAIL,  Sensotrend/sensotrend-uploader#32   
- [ ] CareSens N Premier (Bletoothia käyttäen): Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] CareSens Dual (Bletoothia käyttäen): Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [x] Dexcom: Date: 6.8.2020, Uploader rel: ?, Result: OK (G6, lukulaite ?) 
- [ ] Insulet OmniPod: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Insulet OmniPod DASH: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Medtronic 523 (Contour Next Link -mittaria käyttäen): Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Medtronic 723 (Contour Next Link): Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Medtronic Veo (Contour Next Link): Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Medtronic 530G (Contour Next Link): Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Medtronic 630G (Contour Next Link 2.4): Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [x] Medtronic 640G (Contour Next Link 2.4): Date: 16.9.2020, Uploader rel: 2.31.0, Result: PASS
- [x] Medtronic 670G (Contour Next Link 2.4): Date: 7.12.2020, Uploader rel: ?, Result: PASS 
- [ ] OneTouch Verio: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Verio Flex: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Verio Reflect: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] OneTouch VerioIQ: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] OneTouch UltraMini: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] OneTouch Ultra 2: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Roche Accu-Chek Aviva Connect: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Roche Accu-Chek Guide: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Roche Accu-Chek Guide Me: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Tandem: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Trividia Health True Metrix: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] True Metrix Air: Date: dd.mm.yyyy, Uploader rel: release number, Result: 
- [ ] Trividia Health True Metrix Go: Date: dd.mm.yyyy, Uploader rel: release number, Result: 

Toimivuus selaimilla:
- [x] Chrome: Date: 8.12.2020, Browser ver.: 87.0.4280.88, Result: PASS
- [x] Edge: Date: 8.12.2020, Browser ver.: 87.0.664.55, Result: PASS
- [x] Firefox: Date: 8.12.2020, Browser ver.: 83.0, Result: PASS
- [ ] IE: Date: 8.12.2020, Browser ver.: 11.1198.18362.0, Result: FAIL, https://github.com/Sensotrend/sensotrend-connect-ui/issues/8

**Comment by HannuHyttinen** [comment]
Testin as much as possible. Can be closed.
