### ISSUE TITLE
Localize installation instructions on OSX

### ISSUE THREAD

**Issue by mrinnetmaki** [Sensotrend/sensotrend-uploader#38]
### 1. Description
Currently the installation instructions are in English.
They should be in Finnish for the Finnish version.

![image](https://user-images.githubusercontent.com/5329276/102142449-1a623a80-3e6b-11eb-8a71-917762bb0047.png)

### 2. Requirements and dependencies
**Known requirements for**
- **functional:** 
- **performance:** 
- **usability:** 
- **safety:** 

**Dependencies on other issues:** 

### 3. Implementation details
**Implementation plan:**
**Target schedule:** 

### 3.1 OWASP top 10
[https://github.com/OWASP/www-project-top-ten/blob/master/index.md](https://github.com/OWASP/www-project-top-ten/blob/master/index.md)
- [ ] **1 Injection** - [comments]
- [ ] **2 Broken Authentication** - [comments]
- [ ] **3 Sensitive Data Exposure** - [comments]
- [ ] **4 XML External Entities (XXE)** - [comments]
- [ ] **5 Broken Access Control** - [comments]
- [ ] **6 Security Misconfiguration** - [comments]
- [ ] **7 Cross-Site Scripting XSS** - [comments]
- [ ] **8 Insecure Deserialization** - [comments]
- [ ] **9 Using Components with Known Vulnerabilities** - [comments]
- [ ] **10 Insufficient Logging & Monitoring** - [comments]

### 4. Verification
**Verification plan:**
To be verifified by following steps:

1. [Test step 1]
2. [Test step 2]

**Verification results:**
- [ ] 1. Pass/Fail (SW version, date)
- [ ] 2. Pass/Fail (SW version, date)

**Comment by mrinnetmaki** [comment]
The file that needs to be changed (or localized?) is https://github.com/Sensotrend/sensotrend-uploader/blob/master/resources/background.tiff, I believe.

**Comment by HannuHyttinen** [comment]
Own finnish installation instruction have been launched a long time ago. No need to this fix anymore.
