### ISSUE TITLE
LibreView .csv support / glucose values

### ISSUE THREAD

**Issue by HannuHyttinen** [Sensotrend/sensotrend-uploader#73]
### 1. Description
Importing the LibreView .csv support from Tidepool Uplodaer to Sensotrend Uploader.
Released in [Tidepool Uploader 2.41.0](https://github.com/tidepool-org/uploader/releases/tag/v2.41.0).
Tidepool implementation details can be found from https://github.com/tidepool-org/uploader/pull/1431
Note: This feature includes transferring the glucose values only. Eg. insulin doses stored to the LibreView are not transferred in the implementation made by Tidepool.

### 2. Requirements
**Known requirements for**
- **customer:** Couple of our customers have already asked, when this feature is available. Their requirements are not known in the detailed level. -> They could be use as a beta-tester group.  
- **functionality:** 1. Glucose values are correctly transferred to the KantaPHR. 2. Should be working with .csv files, which are generated by LibreView with setup used in Finland. (Finnish language + minimum date formats DD-MM-YYYY and YYYY-MM-DD. Date format MM-DD-YYYY is nice to have.) 
- **usability:** Similar usability as in the other data transfers features. 
- **regulation:** Nothing special.

- [ ] Design and development inputs have approved by [name, date].

### 3. Implementation details
**Implementation plan:**
**Target schedule:** 

### 4. Verification
**Verification plan:**
To be verified by following test cases:

1. **Date format DD-MM-YYYY:** Transfer a [basic test file (including cgm and blood clugose) in date format DD-MM-YYYY](https://drive.google.com/open?id=1PP-BFK6Wx32ULeU_WmcMu730Ahm38Y50&authuser=hanhytti%40gmail.com&usp=drive_fs). -> The data is transferred correctly to the KantaPHR.
2. **Date format YYYY-MM-DD:** Transfer a [basic test file (including cgm and blood clugose) in date format YYYY-MM-DD](https://drive.google.com/open?id=1PUqi_vZ2i3agdUwc65ZVvpfIVaZXo9Gq&authuser=hanhytti%40gmail.com&usp=drive_fs). -> The data is transferred correctly to the KantaPHR.
3. **Date format MM-DD-YYYY:** Transfer a [basic test file (including cgm and blood clugose) in date format MM-DD-YYYY](https://drive.google.com/open?id=1PiOaTTuxiCiHanQyyuDF-HB82cfd_zGM&authuser=hanhytti%40gmail.com&usp=drive_fs) . -> Nothing unexpected happens.
4. **12 h time format:** Transfer basic test file (including cgm and blood clugose) in 12 h time format. -> The data is transferred correctly to the KantaPHR.
5. **24 h time format:** Transfer basic test file (including cgm and blood clugose) in 24 h time format. -> The data is transferred correctly to the KantaPHR.
6. **All data types:** Transfer a basic test file including as many type of data as possible (insulin doses, nutrition, exercise, ketones,...) -> Glucose values are transferred correctly to the KantaPHR and nothing unexpected happens.
7. **Real world data:** Transfer a [big .csv file with real world data](https://drive.google.com/open?id=1PxtWOI_LaWNVXMBr8fDsAcVNeH03-vN_&authuser=hanhytti%40gmail.com&usp=drive_fs). -> Glucose values are transferred correctly to the KantaPHR and nothing unexpected happens.
8. **Data transfer error:** Try to tranfer an incorrect file. -> A finnish error message is visible.

**Verification results:**
- [ ] 1. Pass/Fail (SW version, date, verifier)
- [ ] 2. Pass/Fail (SW version, date, verifier)
- [ ] 3. Pass/Fail (SW version, date, verifier)
- [ ] 4. Pass/Fail (SW version, date, verifier)
- [ ] 5. Pass/Fail (SW version, date, verifier)
- [ ] 6. Pass/Fail (SW version, date, verifier)
- [ ] 7. Pass/Fail (SW version, date, verifier)
- [ ] 8. Pass/Fail (SW version, date, verifier)
