### ISSUE TITLE
Improvement for e-instruction regulation

### ISSUE THREAD

**Issue by HannuHyttinen** [Sensotrend/sensotrend-uploader#74]
### 1. Description
A new EU regulation for electronic instruction (2021/2226) is available. Some additions to the labeling are needed.

### 2. Requirements
**Known requirements for**
- **customer:** None
- **functionality:** None
- **usability:** None
- **regulation:** EU regulation 2021/2226, article 6, clause 1 and 3d.

- [x] Design and development inputs have approved by Hannu 24.2.2022.

### 3. Implementation details
**Implementation plan:** https://github.com/Sensotrend/sensotrend-connect-ui/pull/46
**Target schedule:** February 2022

### 4. Verification
**Verification plan:**
To be verified by following test cases:

1. **Labeling/e-instruction/fi** Check that reguired clauses (EU regulation 2021/2226, article 6, clause 1 and 3d) can be found from finnish user instruction. 
2. **Labeling/e-instruction/en** Check that reguired clauses (EU regulation 2021/2226, article 6, clause 1 and 3d) can be found from english user instruction. 
3. **Labeling/e-instruction/sv** Check that reguired clauses (EU regulation 2021/2226, article 6, clause 1 and 3d) can be found from swedish label. 

**Verification results:**
- [x] 1. Pass (v.2.4.3, 24.2.2022, local env, Hannu)
- [x] 2. Pass (v.2.4.3, 24.2.2022, local env, Hannu)
- [x] 3. Pass (v.2.4.3, 24.2.2022, local env, Hannu)
