### ISSUE TITLE
Font size increase for kiosk mode

### ISSUE THREAD

**Issue by JaWetter** [Sensotrend/sensotrend-uploader#87]
When creating a request, please fill in parts 1 and 2 with as much information as possible. A good description is most important for us. Fields in the part 2 can also be filled when analyzing the issue.

### 1. Description
Font size is too small for the kiosk, it needs to be increased.

### 2. Requirements
**Known requirements for**
- **customer:**
- **functionality (incl. [62304, ch. 5.2.2 sublauses a,b,d](https://drive.google.com/file/d/19vfHS2bDeDMbb1QquLW44N_cBbctIE00/view?usp=sharing)):** 
- **usability (incl. [62304, ch. 5.2.2 sublause f](https://drive.google.com/file/d/19vfHS2bDeDMbb1QquLW44N_cBbctIE00/view?usp=sharing)):** 
- **regulation (incl. [62304, ch. 5.2.2 sublause l](https://drive.google.com/file/d/19vfHS2bDeDMbb1QquLW44N_cBbctIE00/view?usp=sharing)):** 
- **any other mentioned in [62304, ch. 5.2.2](https://drive.google.com/file/d/19vfHS2bDeDMbb1QquLW44N_cBbctIE00/view?usp=sharing):** 

- [ ] Design and development inputs have approved by [name, date].

### 3. Implementation details
**Implementation plan:**
**Target schedule:** 

### 4. Verification
**Verification plan:**
To be verified by following test cases:

1. [Test case 1]
2. [Test case 2]

**Verification results:**
- [ ] 1. Pass/Fail (SW version, date, verifier)
- [ ] 2. Pass/Fail (SW version, date, verifier)

## Traceability

_instruction: Check that the issue is linked to at least one pull request, if not then link it_

- [ ] This issue(input) has been linked to a pull request(output)
